name: Generate requirements.txt

on:
  push:
    branches:
      - main
      - development

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  
    - name: Automatic requirements.txt for Python Project
      uses: ryan-rozario/pipreqs-action@master
      with:
        PROJECT_PATH: .
        REQUIREMENT_PATH: ./requirements.txt
