name: Generate requirements.txt

on:
  push:
    branches:
      - main
      - development

jobs:
  generate-requirements:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.TOKEN }}
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipreqs
        
    - name: Generate requirements.txt
      run: |
        python -m pipreqs.pipreqs --force
        ls
      
    - name: Commit changes
      run: |
        git config --local user.email "hothaison2005@gmail.com"
        git config --local user.name "thaisonho"
        git add requirements.txt
        git commit -m "Auto-generate requirements.txt" || echo "No changes to commit"
        git push
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
